### ISSUE TITLE
broken, unused method output

### ISSUE THREAD

**Issue by marlonrichert** [Artur-/TestCodeGenerator#8]
This incomplete method is never called:
`public IndexedContainer getDataSource1() {IndexedContainer ic = new IndexedContainer();ic.addContainerProperty("",`
It ends abruptly in a comma, after which the method `public IndexedContainer getDataSource2()` starts.

**Comment by ghost** [comment]
Stack trace?

**Comment by marlonrichert** [comment]
None that I am aware of. Ask Thomas; he passed me the output. I just tried to get it to work (and failed).
